### ISSUE TITLE
where to get amd opencl sdk

### ISSUE THREAD

**Issue by merlinzone** [GPUOpen-LibrariesAndSDKs/OCL-SDK#1]
Using ubuntu 16.04, want use opencl sdk. opencl zone web has no opencl sdk, github OCL-SDK project only have license.md in zip and tar. Where to get OCL-SDK for linux

**Comment by BenjaminCoquelle** [comment]
You will find the library to link against in the driver install path (/opt/amdgpu-pro*)
You can get the headers using your apt.
sudo apt-get install opencl-headers

I hope this helps

**Comment by int03h** [comment]
So this link : 
![2017-07-27 7](https://user-images.githubusercontent.com/5482481/28701433-371f4c1e-7324-11e7-9acb-12403783975e.png)

Takes you to this link : 

![2017-07-27 8](https://user-images.githubusercontent.com/5482481/28701441-49276b94-7324-11e7-89b3-0b5b00bb9770.png)

Which then brings you to this empty github ?  

And then this issue with your comment points us back to the driver ? I actually did link against it and it works even without the AMDAPPSDK (which was the official "old" opencl stack and the ADL SDK). It  would be nice if it was mentioned somewhere that the driver has a stand-alone replacement to the SDK but then what do we use for  ADL ?  ) 

May I also point out that this http://developer.amd.com/resources/open-source/  takes you to Kronos web page https://www.khronos.org/opencl/  which is worthless to us alone. ( as you said we can get the headers via apt , but that doesn't help if the opencl stack isn't properly in place ) 

And then .. just to make it even more interesting .. https://rocm.github.io/install.html (rocm 1.6) has a opencl stack TOO.. but with rocm KFD instead. 

The 17.20 from the Frontier VEGA driver looks some sort of attempt at doing this, but then again I am not really sure because it is focused on ROCM KFD and HSA which is confusing from an opencl 
 perspective, because it uses LLVM and I guess CLANG. I can get my stuff compiled using the KFD and GCC but not LLVM yet. Bottomline.. I am very  very confused about what direction I need to go in. 

I see the general release of 17.30 has just been released, hopefully it  still had the opencl libs. 

The marketing stuff on the VEGA page explains it a little, but the technical stuff doesn't at all. 

I guess what I am asking .. which stack is the AMD focusing on for openCL, and if it's ROCM / HSA is the expectation from AMD that we move everything over to LLVM? IF so, can you point us to some docs that can help us compile our stuff or is this it ? Your compiler or bust  ? http://gpuopen.com/opencl-rocm1-6/ ? ? 

This is CRAZILY CONFUSING for something that was so "simple" for us .. 
![image](https://user-images.githubusercontent.com/5482481/28702175-3bd2b282-7329-11e7-8009-61307999c3f8.png)

**Comment by BenjaminCoquelle** [comment]
If you use the ROCm stack you will get everything you need (headers and libraries) to compile an opencl program directly.
On ROCm stack OpenCL comes from this package
sudo apt-get install rocm-opencl-dev
https://github.com/RadeonOpenCompute/ROCm

If you use amdgpu-pro stack. Then the driver comes with the OpenCL library to link against.
You just need to fetch the opencl headers from your repo.

So here we are just posting a light version of the SDK for windows as on Linux you can get everything you need from the drivers directly

ADL is not supported on linux

**Comment by int03h** [comment]
Thanks Benjamin.  It's still not clear to me though: 

What is the difference between OpenCL obtained via ROCm (the KFD driver) and the one that is obtained via the driver?

Would it be fair to say that ROCm is the developer "way" and the driver is the end-user way  ? 

Thanks.

**Comment by BenjaminCoquelle** [comment]
Not really.
These are two different stacks with different purposes, you can have a end user using ROCm, albeit it will likely only happen at the enterprise level.
You can consider ROCm as a pure compute headless platform. While amdgpu pro is the traditional graphics driver. 
Both stack support OpenCL
